spring:
  datasource:
    url: jdbc:postgresql://192.168.198.31:5432/vassilev-db
    username: vassilev
    password: vassilev
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase-master.xml
    enabled: true

log4j:
  appender:
    file: test-app-2.log