spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-app
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase-master.xml
    enabled: true

log4j:
  appender:
    file: test-app-2.log