spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: liquibase-master.xml
    enabled: true

log4j:
  appender:
    file: test-app-2.log
